In [1]:
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [2]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [3]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("An array initialized with all zeros:\n", c)

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# Create a constant value array of complex type
d = np.full((3, 3), -6, dtype = 'complex')
print ("An array initialized with all 6s." 
            "Array type is complex:\n", d)

An array initialized with all 6s.Array type is complex:
 [[-6.+0.j -6.+0.j -6.+0.j]
 [-6.+0.j -6.+0.j -6.+0.j]
 [-6.+0.j -6.+0.j -6.+0.j]]


In [6]:
# Create an array with random values
e = np.random.random((2, 2))
print ("A random array:\n", e)

A random array:
 [[0.17648464 0.0409043 ]
 [0.63850958 0.12974748]]


In [7]:
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("A sequential array with steps of 5:\n", f)

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [9]:

# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)
print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [10]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()

print ("Original array:\n", arr)
print ("Fattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
