In [2]:
import numpy as np
#Creating 1D Array
n1=np.array([3,4,5,6])
print(n1)

[3 4 5 6]


In [3]:
#Creating 2D Array
n2=np.array([[3,5,6,7],[4,5,6,7]])
print(n2)

[[3 5 6 7]
 [4 5 6 7]]


In [4]:
#Zero filled 2D Array
n3=np.zeros([3,5],dtype='int32')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
#Array filled with ones
n4=np.ones([2,3,3],dtype='int32')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [6]:
#Empty Array
n5=np.empty([1,3])
print(n5)

[[0.  0.5 1. ]]


In [7]:
#Creating array with range of values
n6=np.arange(9,15,0.2)
print(n6)

[ 9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6
 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4
 14.6 14.8]


In [8]:
n7=np.arange(-5,11,5)
print(n7)

[-5  0  5 10]


In [9]:
#Linearly seperated Entries
n8=np.linspace(0,22,num=5)
print(n8)

[ 0.   5.5 11.  16.5 22. ]


In [10]:
#Creating array with a element
n9=np.full([2,5],99)
print(n9)       

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [11]:
#Creating a empty array and fill that array with element
n5.fill(9)
print(n5)

[[9. 9. 9.]]


# Accessing index and slicing

In [12]:
print(n1[0])

3


In [13]:
print(n1[-1])

6


In [14]:
print(n2[1,0])

4


In [15]:
print(n2[1,:])

[4 5 6 7]


In [16]:
print(n2[:,3])

[7 7]


In [17]:
#Changing a element in array
n4[1,1,2] = 10
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1 10]
  [ 1  1  1]]]


# Size and Shape

In [18]:
print(n4.ndim) #gives number of dimensions or axes

3


In [19]:
print(n4.shape)

(2, 3, 3)


In [20]:
print(n4.size) #Total elements

18


In [21]:
print(n4.itemsize) #Size to store

4


In [22]:
print(n4.nbytes) # 4*18

72


In [23]:
print(n4.dtype)

int32


# Sorting

In [24]:
n10=np.array([3,4,1,9,5,10,8,7])
np.sort(n10)

array([ 1,  3,  4,  5,  7,  8,  9, 10])

In [25]:
n11=np.array([[[6,2,7],[5,10,1]]])
np.sort(n11)
print(n11[0][0][1])

2


In [26]:
np.sort(n11,axis=0) #column wise sort

array([[[ 6,  2,  7],
        [ 5, 10,  1]]])

In [27]:
np.sort(n11,axis=1) #row wise sort(default)

array([[[ 5,  2,  1],
        [ 6, 10,  7]]])

# Reshaping and Array Conversions

In [28]:
n12=n10.reshape(4,2)
print(n12)

[[ 3  4]
 [ 1  9]
 [ 5 10]
 [ 8  7]]


In [29]:
n13=np.arange(4)
print(n13)
n14=np.arange(5,9)
print(n14)
n15=np.concatenate((n13,n14))
print(n15)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [30]:
#Converting 1D Array to 2D Array(Method 1)
n16=np.arange(8)
print(n16)
n17=n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18=n16[:,np.newaxis]
print(n18)
print(n18.shape)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [31]:
#Converting 1D Array to 2D Array(Method 2)
n19=np.expand_dims(n16,axis=0)
print(n19)

[[0 1 2 3 4 5 6 7]]


In [32]:
n20=np.expand_dims(n16,axis=1)
print(n20)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


# Advanced Indexing and slicing

In [33]:
n21=np.arange(10)
print(n21)
print(n21[n21>5])

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [34]:
print(n21[(n21>3) & (n21<8)])

[4 5 6 7]


In [35]:
five_up=n21>5 #Boolean Value 
print(five_up)
print(n21[five_up]) #elements

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [36]:
#To get the index
print(np.nonzero(n21>5))

(array([6, 7, 8, 9], dtype=int64),)


In [37]:
print(n21[3:7])

[3 4 5 6]


# Stack and Split

In [38]:
n22 = np.array([[1,2],[3,4]])
n23 = np.array([[5,6],[7,8]])
np.hstack((n22,n23)) #Horizontal stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
np.vstack((n22,n23)) #Vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
n24=np.arange(20)
print(n24)
np.hsplit(n24,4) #Splitting into 4 different arrays

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

# Copy

In [41]:
n25=n24[0:5] #shallow copy
n24[0] = 100
print(n24)
print(n25)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4]


In [42]:
#Deep copy
n24[1] = 1
n26=n24.copy()
print(n26)
n24[1]=200
print(n24)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


# Math

In [43]:
print(n22)
print(n23)
print(n22+n23)
print(n22*n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [44]:
print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*10)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
290
100
1
[1000   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190]


In [45]:
print(np.cos(n26))

[ 0.86231887  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


# Random Numbers

In [46]:
np.random.rand(3,3)

array([[0.20922583, 0.04432909, 0.3573768 ],
       [0.33422958, 0.39924499, 0.69234104],
       [0.35148889, 0.81124693, 0.47108199]])

In [47]:
np.random.randint(20,size=(4,2))

array([[ 0,  8],
       [16,  4],
       [ 8, 10],
       [19, 16]])

In [48]:
arr5=np.array([1,2,3,4,5])
print(arr5[1])
arr6=np.array([[1,2,3,4],[5,6,7,8]])
print(arr6[0][2])
arr7=np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr7[0][0][1])

2
3
2
