In [2]:
import numpy as np

#creation

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([1, 2, 3, 4], ndmin=5)
print("5d array values ", e)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


5d array values  [[[[[1 2 3 4]]]]]
0
1
2
3
5


In [3]:
#indexing
print("5d array ",e[0][0][0][0][3])
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("indexing ",arr[1,4])
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("indexing ",arr[0, 1, 2])

5d array  4
indexing  10
indexing  6


In [4]:
#negative indexing
arr = np.array([[1,2,3,-4,-5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[0, -2])

Last element from 2nd dim:  -4


In [5]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("slicing ",arr[0:5])

slicing  [1 2 3 4 5]


In [6]:
#negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("negative slicing", arr[-3:-1])

print(arr[1:5:2])
print(arr[::2])

negative slicing [5 6]
[2 4]
[1 3 5 7]


In [7]:
#Slicing 2D Array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],  [11, 12, 13, 14, 15]])
print(arr[1, 1:4])
print("arr 2d Slice", arr[0:3, 1])
print("arr 2d Slice flatten", arr[0:3, 1:3])

[7 8 9]
arr 2d Slice [ 2  7 12]
arr 2d Slice flatten [[ 2  3]
 [ 7  8]
 [12 13]]


In [8]:
#data types
arr = np.array([1, 2, 3, 4])
print("type ",arr.dtype)
arr = np.array(['apple', 'banana', 'cherries'])
print("type ",arr.dtype)

type  int32
type  <U8


In [9]:
arr = np.array(['ABCD','BSD','CSSS'], dtype='S2') #related to slicing
print(arr)
print(arr.dtype)
arr = np.array([14, 127, 3, 4], dtype='i1') #Bits
print(arr)
print(arr.dtype)

[b'AB' b'BS' b'CS']
|S2
[ 14 127   3   4]
int8


In [10]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('S')
#newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[b'1.1' b'2.1' b'3.1']
|S32


In [11]:
#Copy and View

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [12]:
arr = np.array([1, 2, 3, 4, 5])
y = arr.view()
arr[0] = 42
print(arr)
print(y)

print(x.base)
print(y.base)

[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [13]:
#Shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [14]:
#Reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
#iteration
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [16]:
for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    print("2d " ,y)
    for z in y:
      print("3d ", z)

2d  [1 2 3]
3d  1
3d  2
3d  3
2d  [4 5 6]
3d  4
3d  5
3d  6
2d  [7 8 9]
3d  7
3d  8
3d  9
2d  [10 11 12]
3d  10
3d  11
3d  12


In [18]:
#nditer

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print("nditer " ,x)
print(arr.shape)

nditer  1
nditer  2
nditer  3
nditer  4
nditer  5
nditer  6
nditer  7
nditer  8
(2, 2, 2)


In [19]:
#joins

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print("axis 0 ",arr)

axis 0  [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
arr = np.concatenate((arr1, arr2), axis=1)
print("axis 1 ",arr)

axis 1  [[1 2 5 6]
 [3 4 7 8]]


In [22]:
#stack - used to join a sequence of arrays along a new axis

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print("stack ",arr)
arr = np.stack((arr1, arr2), axis=0)
print("stack ",arr)
arr = np.hstack((arr1, arr2))
print("hstack ",arr)
arr = np.vstack((arr1, arr2))
print("vstack ",arr)
arr = np.dstack((arr1, arr2))
print("dstack ",arr)

stack  [[1 4]
 [2 5]
 [3 6]]
stack  [[1 2 3]
 [4 5 6]]
hstack  [1 2 3 4 5 6]
vstack  [[1 2 3]
 [4 5 6]]
dstack  [[[1 4]
  [2 5]
  [3 6]]]
