In [6]:
from numpy import random

x = random.randint(100)

print(x)

99


In [9]:
from numpy import random

x = random.rand()

print(x)

0.4379402235600576


In [14]:
from numpy import random

x = random.rand(5)

print(x)

[0.27363119 0.70187149 0.58354684 0.24151239 0.6973422 ]


In [4]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[ 8 51 77 87 19]


In [7]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[49 20 57 40 83]
 [83 26 77 65 15]
 [ 8 10 84 32 75]]


In [15]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.21644147 0.95403969 0.82461921 0.850513   0.79014493]
 [0.76595692 0.80137594 0.32490351 0.20643843 0.73264078]
 [0.33904501 0.36463148 0.32886827 0.04909546 0.32587537]]


In [19]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [21]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 5 7 7]
 [9 7 9 3 3]
 [7 7 7 3 5]]
